server:
  port: 8003
  max-http-header-size: 65536
  forward-headers-strategy: framework

project:
  httpProtocol: 'http://'
  host: 'localhost'
  allowOrigin: '*'

spring:
  application:
    name: PROJECT-MANAGEMENT-LOCAL
  datasource:
    url: jdbc:sqlserver://3.111.194.124:1433;databaseName=kirkland;encrypt=true;TrustServerCertificate=true;
    username: kirkland_dev
    password: Nextq_123
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '${project.httpProtocol}${project.host}:8761/eureka/'
  instance:
    hostname: ${project.host}
    prefer-ip-address: true

logging:
  level:
    root: INFO
  file:
    name: logs/project-management/project-management.log
    total-size-cap: 30GB
    max-size: 5MB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    rolling-file-name: logs/project-management-%d{yyyy-MM-dd}.%i.log