server:
  port: 8005
  max-http-header-size: 65536

financial:
  httpProtocol: 'http://'
  host: 'localhost'
  allowOrigin: '*'

spring:
  application:
    name: FINANCIAL-MANAGEMENT-LOCAL
  datasource:
    url: jdbc:postgresql://aiml-dev-db.cbtaanq5yhb4.us-east-1.rds.amazonaws.com:5432/kirkland?useSSL=false&currentSchema=org_manager
    username: bombora_ui
    password: bombora_ui
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '${financial.httpProtocol}${financial.host}:8761/eureka/'
  instance:
    hostname: ${financial.host}
    prefer-ip-address: true

logging:
  level:
    root: INFO
  file:
    name: logs/financial-management/financial-management.log
    total-size-cap: 30GB
    max-size: 5MB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    rolling-file-name: logs/financial-management-%d{yyyy-MM-dd}.%i.log