server:
  port: 8001
  max-http-header-size: 65536
  forward-headers-strategy: framework
  ssl:
    enabled: true
    key-store: "classpath:cacerts.jks"
    key-store-password: changeit
    key-store-type: jks
    key-alias: nextq
    trust-store: "classpath:cacerts.jks"
    trust-store-password: changeit

gateway:
  httpProtocol: 'https://'
  host: 'demand.nextq.ai'
  url: '${gateway.httpProtocol}${gateway.host}:'

spring:
  application:
    name: GATEWAY-DEV
  datasource:
    url: jdbc:sqlserver://3.111.194.124:1433;databaseName=kirkland;encrypt=true;TrustServerCertificate=true;
    username: kirkland_dev
    password: Nextq_123
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SETTING-MANAGEMENT-DEV
          uri: lb://USER-SETTING-MANAGEMENT-DEV
          predicates:
            - Path=/user-setting/**
          filters:
          - PreGatewayFilter
          
        - id: RESOURCE-MANAGEMENT-DEV
          uri: lb://RESOURCE-MANAGEMENT-DEV
          predicates:
            - Path=/resource/**
          filters:
          - PreGatewayFilter
          
        - id: PROJECT-MANAGEMENT-DEV
          uri: lb://PROJECT-MANAGEMENT-DEV
          predicates:
            - Path=/project/**
          filters:
          - PreGatewayFilter    

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: '${gateway.url}8761/eureka/'
  instance:
    hostname: ${gateway.host}
    prefer-ip-address: false
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}
    statusPageUrl: '${gateway.httpProtocol}${eureka.instance.hostname}:${server.port}/info'
    healthCheckUrl: '${gateway.httpProtocol}${eureka.instance.hostname}:${server.port}/health'
    homePageUrl: '${gateway.httpProtocol}${eureka.instance.hostname}:${server.port}/'

springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none

logging:
  level:
    root: INFO
  file:
    name: logs/gateway/gateway.log
    total-size-cap: 30GB
    max-size: 5MB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    rolling-file-name: logs/gateway-%d{yyyy-MM-dd}.%i.log