spring:
  application:
    name: EUREKA-SERVER-UAT

eureka-config:
  httpProtocol: 'https://'
  host: 'kirkland.nextq.ai'

server:
  port: 8761
  ssl:
    enabled: true
    key-store: "classpath:cacerts.jks"
    key-store-password: changeit
    key-store-type: jks
    key-alias: nextq
    trust-store: "classpath:cacerts.jks"
    trust-store-password: changeit

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: '${eureka-config.httpProtocol}${eureka-config.host}:8761/eureka/'
  instance:
    hostname: ${eureka-config.host}
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true
    secure-port: ${server.port}

logging:
  level:
    root: INFO
  file:
    name: logs/eureka-server/eureka-server.log
    total-size-cap: 30GB
    max-size: 5MB
  pattern:
    console: "%d %-5level %logger : %msg%n"
    rolling-file-name: logs/eureka-server-%d{yyyy-MM-dd}.%i.log